name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_clean_and_scale_scores.py
      id: test_clean_and_scale_scores-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: pip install pytest numpy
    - name: test_count_values_in_bins.py
      id: test_count_values_in_bins-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: pip install pytest numpy
    - name: test_moving_average.py
      id: test_moving_average-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: pip install pytest numpy
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_CLEAN_AND_SCALE_SCORES-PY_RESULTS: "${{steps.test_clean_and_scale_scores-py.outputs.result}}"
        TEST_COUNT_VALUES_IN_BINS-PY_RESULTS: "${{steps.test_count_values_in_bins-py.outputs.result}}"
        TEST_MOVING_AVERAGE-PY_RESULTS: "${{steps.test_moving_average-py.outputs.result}}"
      with:
        runners: test_clean_and_scale_scores-py,test_count_values_in_bins-py,test_moving_average-py
